In [ ]:
# Script to load and test your hdf5 and ensure it was created properly

In [2]:
import numpy as np
import pandas as pd
import h5py
import sys

/Users/keil/miniconda3/envs/tensorflow/lib/python3.6/site-packages/h5py/__init__.py:36: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  from ._conv import register_converters as _register_converters


In [3]:
import sys

In [4]:
import hdf5_data_loader as loader

In [95]:
TT11T12KHpath_to_hdf5 = '/Users/keil/datasets/LUNA16/64x64x1-patch.hdf5' # 2D
# path_to_hdf5 = '/Users/keil/datasets/LUNA16/64x64x3-patch.hdf5' # 2.5D

hdf5_file = h5py.File(path_to_hdf5, 'r') # open in read-only mode

data_dataset = 'input'
class_dataset = 'output'

In [5]:
path_to_hdf5 = '/Users/keil/datasets/LUNA16/64x64x64-patch-annotations.hdf5' # 2D
# path_to_hdf5 = '/Users/keil/datasets/LUNA16/64x64x3-patch.hdf5' # 2.5D

hdf5_file = h5py.File(path_to_hdf5, 'r') # open in read-only mode

data_dataset = 'input'
class_dataset = 'output'

In [6]:
print('Dataset info and some real data:')
for name in [key for key in hdf5_file.keys()]:
    print(name)
    print(hdf5_file[name]) #name + shape + dtype of the dataset (refer back to extract_patch.py)
    print(hdf5_file[name][0:2]) #get the first 5 rows of the dataset

Dataset info and some real data:
centroid
<HDF5 dataset "centroid": shape (128, 3), type "<f8">
[[ -81.21264213   38.50543905 -161.7782189 ]
 [ 112.2326686     9.72289057 -197.4920729 ]]
diameter
<HDF5 dataset "diameter": shape (128, 1), type "<f8">
[[4.51219017]
 [3.89977046]]
input
<HDF5 dataset "input": shape (128, 262144), type "<f4">
[[-861. -828. -814. ... -433. -759. -818.]
 [  58.   43.   57. ...   40.   42.   60.]]
output
<HDF5 dataset "output": shape (128, 1), type "<i8">
[[1]
 [1]]
subsets
<HDF5 dataset "subsets": shape (128, 1), type "<i8">
[[2]
 [2]]
uuid
<HDF5 dataset "uuid": shape (128, 1), type "|O">
[[b'1.3.6.1.4.1.14519.5.2.1.6279.6001.217697417596902141600884006982']
 [b'1.3.6.1.4.1.14519.5.2.1.6279.6001.217697417596902141600884006982']]


In [9]:
len(hdf5_file['subsets'][:])

128

In [10]:
np.where(hdf5_file['subsets'][:] == 7)

(array([], dtype=int64), array([], dtype=int64))

In [11]:
[key for key in hdf5_file.keys()]

['centroid', 'diameter', 'input', 'output', 'subsets', 'uuid']

indexes for: 
- subsets: dict{subset : [idxs]}
- subsets --> class dict{class : [idxs]}
- subsets --> class 0 --> train/notrain: dict{train/notrain(bool): [idxs]}

In [92]:
test = loader.HDF5Matrix(path_to_hdf5,data_dataset)
test_output = loader.HDF5Matrix(path_to_hdf5,class_dataset)

In [70]:
print('shape: {}'.format(test.shape)) #Gets a numpy-style shape tuple giving the dataset dimensions.
print('dtype: {}'.format(test.dtype)) #Gets the datatype of the dataset
print('ndim: {}'.format(test.ndim)) #Gets the number of dimensions (rank) of the dataset.
print('size: {}'.format(test.size)) #returns np.prod(self.shape)

shape: (875, 4096)
dtype: float32
ndim: 2
size: 3584000


In [71]:
test.__len__()

875

In [72]:
for key in range(3):
    data_row = test.__getitem__(key)
    print(data_row)
    print(len(data_row))

[-892. -840. -789. ...,   28.   31.    4.]
4096
[  37.   34.   10. ..., -872. -859. -854.]
4096
[-947. -895. -825. ..., -762. -784. -746.]
4096


In [73]:
test.__getitem__([0,1,2])

array([[-892., -840., -789., ...,   28.,   31.,    4.],
       [  37.,   34.,   10., ..., -872., -859., -854.],
       [-947., -895., -825., ..., -762., -784., -746.]], dtype=float32)

In [74]:
test.__getitem__([0,2,99,101,600])

array([[-892., -840., -789., ...,   28.,   31.,    4.],
       [-947., -895., -825., ..., -762., -784., -746.],
       [ 241.,  269.,  254., ..., -809., -828., -816.],
       [-929., -951., -869., ...,  205.,  468.,  374.],
       [ 220.,  240.,  231., ..., -899., -899., -926.]], dtype=float32)

In [75]:
test_output.__getitem__([0,2,99,101,600])

array([[0],
       [0],
       [0],
       [0],
       [0]])

### try to augment code to pass a list of idxs

In [88]:
test = loader.HDF5Matrix(path_to_hdf5,data_dataset,start=0, end=3) #0 n-1

In [78]:
x_train = test.__getitem__([0,1,2,3,4,5])

In [79]:
x_test = test.__getitem__([6,7,8])

In [80]:
x_train

array([[-892., -840., -789., ...,   28.,   31.,    4.],
       [  37.,   34.,   10., ..., -872., -859., -854.],
       [-947., -895., -825., ..., -762., -784., -746.],
       [-762., -887., -904., ...,    1.,   44.,  131.],
       [-938., -950., -944., ...,  109.,  100.,  119.],
       [-913., -991., -992., ...,  226.,  215.,  211.]], dtype=float32)

In [81]:
x_test

array([[-984., -977., -961., ...,  -34.,  -49.,  -60.],
       [-878., -898., -948., ...,   88.,   90.,   83.],
       [-906., -904., -902., ...,    5.,   27.,   58.]], dtype=float32)

In [ ]:
print('Dataset info and some real data:')
for name in [key for key in hdf5_file.keys()]:
    print(name)
    print(hdf5_file[name]) #name + shape + dtype of the dataset (refer back to extract_patch.py)
    print(hdf5_file[name][0:5]) #get the first 5 rows of the dataset